// Organisation hierarchy node types
const NODE_TYPES = {
  ORGANISATION: 'ORGANISATION',
  OFFICE_LOCATION: 'OFFICE_LOCATION',
  VERTICAL: 'VERTICAL',
  DEPARTMENT: 'DEPARTMENT',
};

// Valid parent types for hierarchy enforcement
const VALID_PARENT_MAP = {
  ORGANISATION: null,
  OFFICE_LOCATION: 'ORGANISATION',
  VERTICAL: 'OFFICE_LOCATION',
  DEPARTMENT: 'VERTICAL',
};

// User account statuses
const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  LOCKED: 'LOCKED',
};

// Org unit statuses
const ORG_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ARCHIVED: 'ARCHIVED',
};

// Permission effect
const PERMISSION_EFFECT = {
  ALLOW: 'ALLOW',
  DENY: 'DENY',
};

// Module codes
const MODULES = {
  NEWS: 'NEWS',
  DOCUMENTS: 'DOCUMENTS',
  PUSH: 'PUSH',
  DIRECTORY: 'DIRECTORY',
  SEARCH: 'SEARCH',
  SAVED: 'SAVED',
  ANALYTICS: 'ANALYTICS',
  ADMIN: 'ADMIN',
};

// Audit log actions
const AUDIT_ACTIONS = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  TOKEN_REFRESH: 'TOKEN_REFRESH',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  ROLE_DELETED: 'ROLE_DELETED',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  ROLE_UNASSIGNED: 'ROLE_UNASSIGNED',
  ORG_UNIT_CREATED: 'ORG_UNIT_CREATED',
  ORG_UNIT_UPDATED: 'ORG_UNIT_UPDATED',
  ORG_UNIT_DELETED: 'ORG_UNIT_DELETED',
  NEWS_CREATED: 'NEWS_CREATED',
  NEWS_UPDATED: 'NEWS_UPDATED',
  NEWS_DELETED: 'NEWS_DELETED',
  NEWS_PUBLISHED: 'NEWS_PUBLISHED',
  NEWS_ARCHIVED: 'NEWS_ARCHIVED',
  DOC_CREATED: 'DOC_CREATED',
  DOC_UPDATED: 'DOC_UPDATED',
  DOC_DELETED: 'DOC_DELETED',
  DOC_PUBLISHED: 'DOC_PUBLISHED',
  DOC_VERSION_CREATED: 'DOC_VERSION_CREATED',
  PUSH_CREATED: 'PUSH_CREATED',
  PUSH_SENT: 'PUSH_SENT',
  PUSH_CANCELLED: 'PUSH_CANCELLED',
  USER_BULK_IMPORT: 'USER_BULK_IMPORT',
};

// Default tenant ID (used in seeders)
const DEFAULT_TENANT_ID = 1;
const DEFAULT_ORG_UNIT_ID = 1;

module.exports = {
  NODE_TYPES,
  VALID_PARENT_MAP,
  USER_STATUS,
  ORG_STATUS,
  PERMISSION_EFFECT,
  MODULES,
  AUDIT_ACTIONS,
  DEFAULT_TENANT_ID,
  DEFAULT_ORG_UNIT_ID,
};
