/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        'secondary-container': '#e1e3e4',
        'on-tertiary': '#ffffff',
        tertiary: '#755a24',
        'surface-container-low': '#f5f3f6',
        'secondary-fixed-dim': '#c5c7c8',
        'on-surface-variant': '#44474e',
        'on-primary-container': '#46597d',
        'tertiary-container': '#f0cb8a',
        'surface-container': '#efedf1',
        background: '#fbf9fc',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#e6c181',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f2f0f3',
        'surface-container-highest': '#e4e2e5',
        'on-secondary': '#ffffff',
        'on-background': '#1b1b1e',
        outline: '#75777f',
        'on-secondary-fixed-variant': '#454748',
        'surface-bright': '#fbf9fc',
        primary: '#4c5e83',
        'on-secondary-fixed': '#191c1d',
        'on-primary-fixed': '#041b3c',
        'on-surface': '#1b1b1e',
        secondary: '#5c5f60',
        'surface-container-high': '#e9e7eb',
        'primary-fixed-dim': '#b4c7f1',
        'surface-dim': '#dbd9dd',
        'primary-fixed': '#d7e2ff',
        surface: '#fbf9fc',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#6f541f',
        'on-tertiary-fixed': '#271900',
        'inverse-surface': '#303033',
        'secondary-fixed': '#e1e3e4',
        'tertiary-fixed': '#ffdea6',
        'primary-container': '#bdd0fb',
        'inverse-primary': '#b4c7f1',
        'on-primary-fixed-variant': '#34476a',
        'on-secondary-container': '#626566',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#5b430e',
        error: '#ba1a1a',
        'outline-variant': '#c5c6cf',
        'error-container': '#ffdad6',
        'surface-variant': '#e4e2e5',
        'surface-tint': '#4c5e83',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'unit-xl': '2.5rem',
        'unit-xxl': '4rem',
        'unit-lg': '1.5rem',
        'unit-md': '1rem',
        'unit-xs': '0.25rem',
        gutter: '1.5rem',
        'unit-sm': '0.5rem',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        h1: ['Inter'],
        'body-sm': ['Inter'],
        'body-lg': ['Inter'],
        display: ['Inter'],
        h2: ['Inter'],
        'label-caps': ['Inter'],
        h3: ['Inter'],
        'body-md': ['Inter'],
      },
      fontSize: {
        h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        h3: ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
};
